### ISSUE TITLE
nuevo comando: Despido

### ISSUE THREAD

**Issue by JGPenaB** [JGPenaB/Pasante-bot#13]
A veces pasante hace algo que no nos gusta, así que en casos así lo despedimos. La idea es que pasante es como una cuenta que cualquiera puede usar. Si despides a quien usa la cuenta, que se ponga a chillar cuando lo despiden, y otra persona tome el control de la cuenta.

**Ejemplo**:

!despedido

Pasante: NOOOOOOO, NO PUEDES DESPEDIRME CUANDO YO HE HECHO TODO LO QUE ME PEDÍAN,M QUE INGRATO, QUE INHUMANOS NBUHOUISJHFINSIFOIFN

_Cambia el avatar, dando a entender que es otra persona_

Pasante: Buenas, soy el pasante Nro. #. Espero que esto sea una experiencia positiva para todos.

**Características que debe tener:**
- [ ] Chilla y añade texto al azar
- [ ] Cambio de avatar un poco después de chillar
- [ ] Comentarios del recién llegado

A lo mejor hace falta guardar las fotos de los posibles pasantes.

**Comment by darioxlz** [comment]
Creo que esto se podría lograr, para las imágenes podríamos tener una carpeta en el repositorio con varias imágenes enumeradas, unas 10 por ejemplo y elegir una aleatoriamente, igualmente con texto, en un json que tenga varias frases e igual con los comentarios, para llevar el conteo de pasante #X imaginaba usar un json, pero a estar en heroku y que cada mes se reinicie se perdería la cuenta

**Comment by JGPenaB** [comment]
De las imagenes tenia pensado eso, porque obtenerlos desde la red sería complicado, pero más variado. De los posibles comentarios y cantidad de pasantes pensaba en una BDD para evitar el manero rudimentario con archivos locales o características del Discord. Encima con una BDD se podría expandir un poco el comando a futuro para que haya más aleatoriedad.

Otro detalle es que para evitar la desincronía con otros servidores, habría que limitar quién pueda usar el comando.

**Comment by cedaesca** [comment]
Entonces se manejaría con archivos? Podemos hacer un diccionario de mensajes como hice en el refactor de algunos de los comandos, para que se pueda ir expandiendo poco a poco.

Respecto a las imágenes, se puede crear un directorio específico para los perfiles de pasante, como mencionó @josevenezuelapadron 

Hacerlo con BDD requeriría una interfaz...

**Comment by darioxlz** [comment]
Te refieres a una interfaz grafica para lo de la BDD? Para nada, antes usábamos un comando que simulaba los juegos del hambre, que se conectaba a una BDD y decía quien seguía vivo y eso.

Era algo sencillo sin mucho código. Pero creo que al no tener la condición de que heroku se reinicia cada tanto podemos usar archivos. Lo del directorio de imágenes si va

Los mensajes van en un archivo como dice @cedaesca

**Comment by cedaesca** [comment]
Ok. Entonces yo tomo este issue.

**Comment by darioxlz** [comment]
> Ok. Entonces yo tomo este issue.

tu vas a tomar muchas cosas carnal...
