### ISSUE TITLE
Nuevo comando: Avatar

### ISSUE THREAD

**Issue by JGPenaB** [JGPenaB/Pasante-bot#16]
Tomando la idea de Dario Padrón de programar nosotros mismos comandos de Ayana.

comando "Avatar" que coloque el avatar del usuario que ejecutó el comando, o de un usuario que se haya especificado en el comando.

**Ejemplo:**

```
!avatar

Pasante: <coloca mi avatar, ya sea un link o la imagen como tal>

!avatar usuario1

Pasante: <coloca el avatar de usuario1>
`

**Comment by darioxlz** [comment]
Una vez mas tus problemas fueron resueltos con el poder del razonamiento padronico. Cmd añadido y testeado
