### ISSUE TITLE
Nuevo comando: Pick

### ISSUE THREAD

**Issue by JGPenaB** [JGPenaB/Pasante-bot#17]
Tomando la idea de Dario Padrón de programar nosotros mismos comandos de Ayana.

comando "Pick" que elija una opción al azar de un set de opciones separados por comas. Muy sencillo.

```
!pick opcion 1, opcion 2

Pasante: Elegi... opcion 2
```

**Comment by darioxlz** [comment]
Feature añadida exitosamente :dametu****:
